version: '3.9'
services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-scrobpass}
      MARIADB_DATABASE: music-scrobbler
      MARIADB_USER: ${MARIADB_USER:-scrob}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-scrobpass}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  scrobbler:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: scrobbler
    environment:
      SCROBBLER_DB_DSN: mysql+asyncmy://${MARIADB_USER:-scrob}:${MARIADB_PASSWORD:-scrobpass}@mariadb:3306/music-scrobbler
      SCROBBLER_REDIS_URL: redis://redis:6379/0
      SCROBBLER_ANALYZER_QUEUE: scrobbler-analyzer
      SCROBBLER_ANALYZER_PATHS: '["/music"]'
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - ${SCROBBLER_MUSIC_PATH:-./music}:/music:ro

  analyzer-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: analyzer-worker
    environment:
      SCROBBLER_DB_DSN: mysql+asyncmy://${MARIADB_USER:-scrob}:${MARIADB_PASSWORD:-scrobpass}@mariadb:3306/music-scrobbler
      SCROBBLER_REDIS_URL: redis://redis:6379/0
      SCROBBLER_ANALYZER_QUEUE: scrobbler-analyzer
      SCROBBLER_ANALYZER_PATHS: '["/music"]'
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ${SCROBBLER_MUSIC_PATH:-./music}:/music:ro

  phpmyadmin:
    image: phpmyadmin:5
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${MARIADB_USER:-scrob}
      PMA_PASSWORD: ${MARIADB_PASSWORD:-scrobpass}
    ports:
      - "8081:80"
    depends_on:
      mariadb:
        condition: service_healthy
