from __future__ import annotations

from datetime import datetime
from typing import Any, Iterable, Mapping, Tuple, Protocol


class DatabaseAdapter(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...

    async def get_config(self) -> Mapping[str, str]: ...
    async def update_config(self, kv: Mapping[str, str]) -> None: ...

    async def upsert_user(self, username: str) -> int: ...
    async def lookup_artist_id(self, name: str) -> int | None: ...
    async def lookup_genre_id(self, name: str) -> int | None: ...
    async def lookup_album_id(
        self,
        title: str,
        *,
        artist_id: int | None,
        release_year: int | None = None,
    ) -> int | None: ...
    async def lookup_track_id_by_uid(self, track_uid: str | None) -> int | None: ...
    async def lookup_track_details(
        self, *, title: str, artist_id: int | None, album_id: int | None
    ) -> int | None: ...
    async def lookup_track_artist_ids(self, track_id: int) -> list[int]: ...
    async def lookup_track_genre_ids(self, track_id: int) -> list[int]: ...

    async def insert_listen(
        self,
        *,
        user_id: int,
        track_id: int,
        listened_at: datetime,
        source: str,
        source_track_id: str | None,
        position_secs: int | None,
        duration_secs: int | None,
        artist_name_raw: str | None,
        track_title_raw: str | None,
        album_title_raw: str | None,
        artist_ids: Iterable[int],
        genre_ids: Iterable[int],
    ) -> Tuple[int, bool]: ...

    async def fetch_recent_listens(self, limit: int = 10) -> list[dict[str, Any]]: ...
    async def fetch_listens(
        self,
        *,
        period: str,
        value: str | None,
        limit: int,
        offset: int,
    ) -> tuple[list[dict[str, Any]], int]: ...
    async def fetch_listen_detail(self, listen_id: int) -> dict[str, Any] | None: ...
    async def count_listens(self) -> int: ...
    async def delete_all_listens(self) -> None: ...
    async def fetch_listens_for_export(
        self,
        *,
        user: str | None = None,
        since: datetime | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[dict[str, Any]]: ...

    async def stats_artists(
        self, period: str, value: str | None, limit: int, offset: int
    ) -> tuple[list[dict[str, Any]], int]: ...
    async def stats_genres(
        self, period: str, value: str | None, limit: int, offset: int
    ) -> tuple[list[dict[str, Any]], int]: ...
    async def stats_albums(
        self, period: str, value: str | None, limit: int, offset: int
    ) -> tuple[list[dict[str, Any]], int]: ...
    async def stats_tracks(
        self, period: str, value: str | None, limit: int, offset: int
    ) -> tuple[list[dict[str, Any]], int]: ...
    async def stats_top_artist_by_genre(self, year: int) -> list[dict[str, Any]]: ...
    async def stats_time_of_day(self, year: int, period: str) -> list[dict[str, Any]]: ...
    async def artist_insights(self, artist_id: int) -> dict[str, Any] | None: ...
    async def album_insights(self, album_id: int) -> dict[str, Any] | None: ...
